#!/bin/bash
#Author: Rongchuan Sun
#StudentNumber: 23715251

#output header line
echo -e "Name_of_Covered_Entity\tState\tIndividuals_Affected\tDate_of_Breach\tType_of_Breach\tMonth\tYear"


tail -n +2 $1 | while IFS=$'\t' read  -r col1 col2 col3 col4 col5 col6 col7
do
	#To remove everything in the field after the first comma or slash for the column of Type of Breach
	col5=$(echo "$col5" | sed -e 's/\([^"$]\)[,\/].*/\1/g')
	
	#To process Date_of_Breach column, and add a month column and a year column
	if [[ $col4 == *"-"* ]]
	then
		Year=$(echo $col4 | cut -c 7-10)	
		Month=$(echo $col4 | awk -F '/' '{printf("%2d", $1)}' | awk '{sub(/^ /,"");print}')
	elif [[ "$col4" =~ ^[0-9]{1,2}/[0-9]{1,2}/[0-9]{2}$ ]]
	then
		Year=$(echo $col4 | cut -d'/' -f3)
		if [[ 10#${Year} -lt 23 ]]
		then
			Year="20${Year}"
		else
			Year="19${Year}"
		fi
		Month=$(echo $col4 | awk -F '/' '{printf("%2d", $1)}' | awk '{sub(/^ /,"");print}')	
	else
		Year=$(echo "$col4" | cut -d'/' -f3)
		Month=$(echo $col4 | awk -F '/' '{printf("%2d", $1)}' | awk '{sub(/^ /,"");print}')
	fi
	echo -e "$col1\t$col2\t$col3\t$col4\t$col5\t$Month\t$Year"
done
